# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170422_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='terms',
            field=models.TextField(null=True, verbose_name='terms & conditions'),
        ),
    ]
