# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20170422_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='promotor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
