# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='event',
            field=models.IntegerField(),
        ),
    ]
