# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDetail',
        ),
        migrations.AlterModelOptions(
            name='userdetail',
            options={'verbose_name': 'User Detail'},
        ),
    ]
